name: purakaku-python
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.5
  - numpy=1.11.2
  - pandas=0.20.1
  - xarray=0.10
  - numpydoc=0.6.0
  - matplotlib=2.0.0
  - seaborn=0.7.1
  - dask=0.12.0
  - ipython=5.1.0
  - sphinx=1.5
  - netCDF4=1.2.9
  - scikit-learn
  - pip:
    - sphinx-gallery
